name: trivia_quiz_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  shared_preferences: ^2.5.2
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  cloud_firestore: ^5.6.5
  font_awesome_flutter: ^10.8.0
  connectivity_plus: ^6.1.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  animated_custom_dropdown: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/quiz_logo.jpg"

flutter_native_splash:
  android: true
  ios: true
  web: false

  # Background color for a clean and modern look
  color: "#ffffff"  

  # Centered logo for a professional touch
  image: "assets/images/quiz_logo.jpg"

  # Adjusting the image position and size
  android_gravity: center
  ios_content_mode: center

  # Fullscreen mode for a clean splash experience
  fullscreen: true